---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secondary-flux-repo
  namespace: apps
spec:
  interval: 1m0s
  path: ./deploy/dev
  prune: false
  serviceAccountName: secondary-flux-repo
  sourceRef:
    kind: GitRepository
    name: secondary-flux-repo
  targetNamespace: apps

