# /base/applications/monitoring/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fluxcd-gitrepo.yaml
- monitoring-config-kustomization.yaml
- prometheus-kustomization.yaml